#!/bin/bash

# Prepare source for RPM build
# Check for js utils: npm, grunt, bower

set -e

which npm >/dev/null

if [ $? -gt 1 ]; then
    echo "[ERROR] Install 'npm' package: 'dnf install npm'"
    exit 1
fi

which grunt >/dev/null

if [ $? -gt 1 ]; then
    echo "[ERROR] Install 'grunt' package: 'npm install -g grunt-cli'"
    exit 1
fi


which bower >/dev/null

if [ $? -gt 1 ]; then
    echo "[ERROR] Install 'grunt' package: 'npm install -g bower'"
    exit 1
fi

# Cleanup existing release
rm -f *.tar.gz
rm -f *.rpm
rm -f *.log

# Pull new languages strings if .pot exists.
# To generate the .pot execute:
#   grunt lang-extract
if [ -f app/i18n/en_US.pot ]; then
    tx pull -a
    # copy each pos into project directory
    cp .tx/nethserver.Cockpit-api/* api/i18n/
fi

# Install dependecies and build UI and API
npm install && grunt build && grunt lang-compile && grunt release
